markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
gravatar: 123
url: http://localhost:4000
feedburner: christophehamerling
ga: 
disqus: 
twitter: @apisuomi
title: API -manifesti
subtitle: 
author: 
